### ISSUE TITLE
add compression, caching to grammars vhost

### ISSUE THREAD

**Issue by balmas** [alpheios-project/puppet#14]
need to optimize serving of graphics in Allen and Greenough grammar

**Comment by balmas** [comment]
done by compressing graphics and moving the grammars to aws cloudfront

**Comment by balmas** [comment]
@monzug I have moved all of the grammars to the AWS CDN. I think they are working well but please confirm. Thanks!!

**Comment by monzug** [comment]
yes, much better. Back to Index is a little slow when the section has lots of graphics.
e.g. scroll all the Deponent Verbs section to the bottom then click on Back to Index, it takes longer to generate the index.
otherwise it's all good

**Comment by balmas** [comment]
>Back to Index is a little slow when the section has lots of graphics.

that's interesting. Not sure I can do much about it but I'll take a look.

**Comment by monzug** [comment]
just worth mentioning

**Comment by balmas** [comment]
actually I'm not seeing that - it went immediately back to the index for me.

**Comment by monzug** [comment]
ok. will close this one. thanks for checking.
